import "./acceptance-phase-finalization.contract.js";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import childProcess from "node:child_process";
import { syncBuiltinESMExports } from "node:module";
import { fileURLToPath } from "node:url";
import { after, before, describe, mock, test } from "node:test";
import { AcceptancePhaseScenario, acceptanceProviderResponse } from "../../support/acceptance-phase-scenario.js";
import RunClaimNextActionCommand from "../../../src/flow/lib/run-claim-next-action.js";
import { SeedWorkRoot } from "../../support/builders/seed-work-root.js";
import { createTmpDir, removeTmpDir } from "../../support/builders/tmp-dir.js";
import { canonicalDraftDocument } from "../../support/infrastructure/flow-setup.js";
import { requestPayloadPath, requestInput } from "../../support/infrastructure/flow-dispatch-scenario.js";
import { RunReportCommand } from "../../../src/flow/lib/run-report.js";
import { acceptanceDecisionRouteFacts } from "../../../src/flow/lib/definition-route-facts.js";
import { validateExplicitFinalRegressionProceed } from "../../../src/flow/lib/test-artifacts.js";
import { RepairArtifactRegistry } from "../../../src/flow/lib/repair-state-identity.js";
import { UnknownProviderFailure } from "../../../src/lib/agent-failure.js";
import { AcceptanceEvidenceExecutionPlan } from "../../../src/flow/lib/run-acceptance-review.js";
import { PromptExecutionLimit, PromptRequestLimit } from "../../../src/lib/prompt-batching.js";
import { activateNonBlockingPolicy, decisionContextForActiveFlow, recordNonBlockingDecision } from "../../../src/flow/lib/nonblocking.js";
import * as definition from "../../../src/flow/definition.js";
import { acceptancePhaseResultContracts } from "../../support/assertions/acceptance-phase-result.js";
import { assertAcceptanceFinalRegressionEvidence } from "../../support/assertions/acceptance-final-regression.js";

function descriptorProducer(scenario, artifact, nodeId) {
  assert.equal(artifact.descriptor.logicalKey, artifact.descriptor.logicalKey.trim());
  assert.match(artifact.descriptor.hash, /^[a-f0-9]{64}$/);
  const activity = scenario.manager.activityLedger(scenario.specId).find((entry) => entry.id === artifact.descriptor.activityId);
  assert.ok(activity, `${artifact.descriptor.logicalKey} must name its genuine producing Activity`);
  assert.equal(activity.nodeId, nodeId);
  assert.ok(activity.attemptId);
  assert.ok(activity.sequence > 0);
  return activity;
}

function savedReview(scenario) {
  return scenario.commandArtifact("acceptance.review", "acceptance-decision");
}

describe("Acceptance phase canonical producer / reload / consumer scenarios", { concurrency: false }, () => {
  let seed;
  const seedCleanups = [];
  after(() => { for (const cleanup of seedCleanups.reverse()) cleanup(); });
  before(async () => {
    // The only shared object is a read-only seed generated by actual commands.
    // Each test owns a SeedWorkRoot clone, manager and external response fake.
    const scope = { mock, after(cleanup) { seedCleanups.push(cleanup); } };
    seed = await AcceptancePhaseScenario.seed(scope, { frontier: "retro" });
  });

  test("A01 actual 03 evidence produces Retro, full Acceptance, artifactless no-op, regression and Report consumed by 05 admission", async (t) => {
    const scenario = AcceptancePhaseScenario.fromSeed(t, seed);
    const execution = scenario.commandArtifact("test.execute", "retro");
    const executionProducer = descriptorProducer(scenario, execution, "test-execute");
    const resultReview = scenario.commandArtifact("test.result.review", "retro");
    descriptorProducer(scenario, resultReview, "test-result-review");
    assert.equal(resultReview.payload.testExecute.producerActivityId, executionProducer.id);
    assert.equal(resultReview.payload.repairFingerprint, execution.payload.repairFingerprint);
    assert.equal(resultReview.payload.verdict, "pass");
    assert.deepEqual(execution.payload.summary.map(({ id, result }) => ({ id, result })), [{ id: "R1", result: "pass" }]);
    descriptorProducer(scenario, scenario.commandArtifact("impl.review", "acceptance-review"), "impl-review");
    descriptorProducer(scenario, scenario.commandArtifact("impl.gate", "acceptance-review"), "impl-gate");
    await scenario.advanceTo("acceptance-review");
    scenario.reload();
    const retro = scenario.artifact("retro");
    descriptorProducer(scenario, retro, "retro");
    assert.deepEqual(JSON.parse(retro.bytes).summary, {
      total: 1, done: 1, partial: 0, not_done: 0, not_applicable_count: 0,
      deferred_count: 0, na_count: 0, not_testable_count: 0, rate: 1,
      notes: "aggregated from test-execute-result.json",
    });
    const accepted = await scenario.runRegistered("acceptance-review");
    assert.equal(accepted.verdict, "pass", JSON.stringify(accepted));
    scenario.reload();
    const review = savedReview(scenario);
    const acceptanceProducer = descriptorProducer(scenario, review, "acceptance-review");
    const input = scenario.acceptanceContexts.at(-1);
    assert.deepEqual(review.payload.requirementJudgments.map(({ requirementId }) => requirementId), input.requirementIds);
    assert.deepEqual(review.payload.deferredFindings.map(({ findingId }) => findingId), input.deferredFindings.map(({ findingId }) => findingId));
    assert.deepEqual(review.payload.mechanicalBlockers, []);
    assert.equal(scenario.acceptanceCalls.length, 1);
    const decision = scenario.state().findNode("acceptance-decision");
    assert.ok(["done", "skipped"].includes(decision.status));
    assert.equal(scenario.manager.readArtifact({ specId: scenario.specId, logicalKey: "acceptance.decision",
      consumerNodeId: "final-regression", optional: true }), null, "passing Acceptance cannot manufacture a user decision artifact");
    assert.equal(decision.result.stepResult, null, "no-op completion retains its actual source receipt rather than a fabricated user Result");
    assert.ok(decision.result.artifactRefs.some((entry) => entry.kind === "source-step-settlement"),
      "ACCEPTANCE_NOOP_RECEIPT_MISSING: artifactless completion must refer to the owning Acceptance receipt in its transaction");
    assert.ok(acceptanceProducer.result?.draftSettlementReceipt,
      "ACCEPTANCE_NOOP_OWNER_RECEIPT_MISSING: its source must own the exact saved Acceptance settlement");
    const noOpReferences = decision.result.artifactRefs.filter((entry) => entry.kind === "source-step-settlement");
    assert.equal(noOpReferences.length, 1);
    assert.equal(noOpReferences[0].id, acceptanceProducer.result.draftSettlementReceipt.id);
    assert.equal(decision.result.draftSettlementReceipt, null);
    assert.equal(decision.result.confirmedAt, acceptanceProducer.result.confirmedAt);
    assert.equal(scenario.current(), "final-regression");
    const regression = await scenario.runRegistered("final-regression");
    assert.equal(regression.result, "pass", JSON.stringify(regression));
    scenario.reload();
    const final = scenario.commandArtifact("final.regression", "report");
    descriptorProducer(scenario, final, "final-regression");
    assertAcceptanceFinalRegressionEvidence(scenario, final, { result: "pass", exitCode: 0 });
    assert.equal(final.payload.executionBinding.parsedResult, "pass");
    assert.ok(final.payload.executionBinding.testCount > 0);
    assert.equal(final.payload.executionBinding.truncated, false);
    await scenario.advanceTo("report");
    const reportResult = await scenario.runRegistered("report");
    assert.equal(reportResult.result, "ok", JSON.stringify(reportResult));
    scenario.reload();
    const report = scenario.artifact("report");
    descriptorProducer(scenario, report, "report");
    assert.equal(JSON.parse(report.bytes).data.delivery.status, "not_required");
    RunReportCommand.validateFinalEvidence(JSON.parse(report.bytes), { root: scenario.root, artifactRoot: scenario.root });
    await scenario.advanceTo("finalize-commit");
    scenario.reload();
    const commit = await scenario.runRegistered("finalize-commit");
    assert.equal(commit.status, "done", "real 05 consumer must admit the freshly saved report before committing");
    scenario.reload();
    scenario.assertResults(["retro", "acceptance-review", "final-regression", "report"]);
  });

  test("A02 canonical Acceptance finding reaches actual triage and source repair before a new test chain and new Acceptance", async (t) => {
    const scenario = AcceptancePhaseScenario.fromSeed(t, seed, {
      acceptanceResponse: (ordinal, active) => acceptanceProviderResponse(active, { status: ordinal === 1 ? "notMet" : "met" }),
    });
    const originalTests = scenario.commandArtifact("test.execute", "retro");
    const originalReview = scenario.commandArtifact("test.result.review", "retro");
    const prefix = scenario.manager.activityLedger(scenario.specId).map((entry) => entry.id);
    await scenario.advanceTo("acceptance-review");
    const first = await scenario.runRegistered("acceptance-review");
    assert.equal(first.verdict, "repair_required", JSON.stringify(first));
    scenario.reload();
    assert.equal(scenario.current(), "impl-triage");
    const rejected = savedReview(scenario);
    const source = descriptorProducer(scenario, rejected, "acceptance-review");
    assert.equal(scenario.state().findNode("acceptance-review").status, "invalidated");
    for (const id of ["impl-repair", "impl-gate", "retro", "acceptance-decision", "final-regression", "report"]) {
      assert.equal(scenario.state().findNode(id).status, "invalidated", `${id} must be reopened by the fixed Acceptance repair route`);
    }
    for (const id of ["test-execute", "test-result-review", "impl-review"]) {
      assert.equal(scenario.state().findNode(id).status, "done", "existing source evidence remains the lawful triage input until source repair occurs");
    }
    await scenario.advanceTo("impl-repair");
    scenario.reload();
    const triageRequest = scenario.phaseWorkers.find((entry) => entry.stepId === "impl-triage");
    assert.ok(triageRequest, "the actual source worker must consume the saved Acceptance finding");
    const triageInput = requestInput(triageRequest, "acceptance-review.json");
    assert.equal(triageInput.digest, rejected.descriptor.hash);
    assert.deepEqual(triageInput.document, rejected.payload);
    const triage = JSON.parse(scenario.artifact("impl.triage").bytes);
    assert.deepEqual(triage.dispositions.map(({ findingKey, disposition }) => ({ findingKey, disposition })),
      [{ findingKey: "requirement:R1", disposition: "apply" }]);
    const beforeRepair = fs.readFileSync(path.join(scenario.root, "src/implementation.js"), "utf8");
    await scenario.advanceTo("test-execute");
    scenario.reload();
    for (const id of ["test-result-review", "impl-review", "impl-gate", "retro"]) {
      assert.equal(scenario.state().findNode(id).status, "invalidated", `${id} must not reuse evidence after source mutation`);
    }
    assert.notEqual(fs.readFileSync(path.join(scenario.root, "src/implementation.js"), "utf8"), beforeRepair);
    const repair = JSON.parse(scenario.artifact("impl.repair").bytes);
    assert.deepEqual(repair.appliedFindingKeys, ["requirement:R1"]);
    assert.ok(repair.sourceMutationManifest.mutations.length > 0);
    await scenario.advanceTo("acceptance-review");
    scenario.reload();
    const currentTests = scenario.commandArtifact("test.execute", "acceptance-review");
    assert.notEqual(currentTests.descriptor.activityId, originalTests.descriptor.activityId);
    assert.notEqual(currentTests.payload.repairFingerprint, originalTests.payload.repairFingerprint);
    const currentReview = scenario.commandArtifact("test.result.review", "acceptance-review");
    assert.notEqual(currentReview.descriptor.activityId, originalReview.descriptor.activityId);
    assert.equal(currentReview.payload.testExecute.producerActivityId, currentTests.descriptor.activityId);
    assert.equal(currentReview.payload.repairFingerprint, currentTests.payload.repairFingerprint);
    const second = await scenario.runRegistered("acceptance-review");
    assert.equal(second.verdict, "pass", JSON.stringify(second));
    scenario.reload();
    const accepted = savedReview(scenario);
    assert.notEqual(accepted.descriptor.activityId, source.id);
    assert.notEqual(accepted.payload.repairFingerprint, rejected.payload.repairFingerprint);
    const history = scenario.artifactHistory("acceptance.review", "final-regression");
    assert.deepEqual(history.attempts.map((entry) => entry.payload.verdict), ["repair_required", "pass"]);
    assert.deepEqual(history.attempts[0].payload, rejected.payload, "the old rejected finding remains intact rather than being rewritten as PASS");
    assert.deepEqual(scenario.manager.activityLedger(scenario.specId).slice(0, prefix.length).map((entry) => entry.id), prefix);
    assert.equal(scenario.acceptanceCalls.length, 2);
    const beforeReplay = scenario.snapshot();
    const replay = await scenario.acceptDecision("accept_risk_and_continue");
    assert.equal(replay.ok, false, "old Acceptance repair cannot be used as a risk decision after new acceptance");
    assert.deepEqual(scenario.reload().snapshot(), beforeReplay);
    scenario.assertResults(["retro", "acceptance-review"]);
  });

  for (const autoApprove of [true, false]) {
    for (const choice of ["accept_risk_and_continue", "abort"]) {
      test(`A05 semantic risk stays tokenless with autoApprove=${autoApprove}; explicit ${choice} survives reload`, async (t) => {
        const scenario = AcceptancePhaseScenario.fromSeed(t, seed, {
          acceptanceResponse: (_ordinal, active) => acceptanceProviderResponse(active, { status: "notVerifiable" }),
        });
        scenario.manager.setAutoApprove(autoApprove, { specId: scenario.specId });
        scenario.reload();
        await scenario.advanceTo("acceptance-decision");
        scenario.reload();
        const review = savedReview(scenario);
        assert.equal(review.payload.verdict, "user_decision_required");
        assert.deepEqual(review.payload.mechanicalBlockers, []);
        const awaiting = await scenario.next();
        assert.equal(awaiting.directive.kind, "await_user_decision");
        assert.equal(awaiting.requires_approval, false);
        assert.equal(awaiting.approval_token ?? null, null);
        const before = scenario.snapshot();
        const calls = scenario.acceptanceCalls.length;
        const repeated = await scenario.dispatch(3);
        assert.equal(repeated.dispatch.boundary, "await_user_decision");
        assert.deepEqual(scenario.reload().snapshot(), before, "approval policy cannot accept risk or change its Await");
        assert.equal(scenario.acceptanceCalls.length, calls);
        const resolved = await scenario.acceptDecision(choice);
        assert.equal(resolved.choice, choice, JSON.stringify(resolved));
        scenario.reload();
        const decision = scenario.commandArtifact("acceptance.decision", "final-regression");
        descriptorProducer(scenario, decision, "acceptance-decision");
        assert.equal(decision.payload.acceptanceReviewDigest, review.descriptor.hash);
        assert.equal(decision.payload.acceptanceReviewAttempt, review.attempt);
        assert.equal(decision.payload.repairFingerprint, review.payload.repairFingerprint);
        assert.ok(fs.existsSync(scenario.root), "park must preserve the owned worktree and source");
        if (choice === "abort") {
          assert.equal(scenario.state().lifecycle.state, "parked");
          assert.equal(scenario.state().findNode("final-regression").status, "pending");
        } else {
          assert.equal(scenario.current(), "final-regression");
          const issues = JSON.parse(scenario.artifact("issue.log").bytes).entries;
          assert.equal(issues.filter((entry) => entry.step === "acceptance-decision").length, 1);
          assert.equal(issues.find((entry) => entry.step === "acceptance-decision").repairFingerprint, review.payload.repairFingerprint);
        }
        scenario.assertResults(["acceptance-review", "acceptance-decision"]);
      });
    }
  }

  for (const [missing, failure] of [
    ["test.execute", "missing"], ["test.result.review", "missing"], ["impl.review", "missing"], ["impl.gate", "missing"],
    ["test.execute", "invalid"],
  ]) {
    test(`A05 physical ${failure} ${missing} is refused before provider or canonical publication and restoration preserves exact authority`, async (t) => {
      const scenario = AcceptancePhaseScenario.fromSeed(t, seed);
      await scenario.advanceTo("acceptance-review");
      scenario.reload();
      const artifact = scenario.artifact(missing);
      const before = scenario.snapshot();
      const location = scenario.manager.specLocation(scenario.specId);
      const authority = [location.flowStateFile, location.activitiesFile, location.catalogFile]
        .map((file) => ({ file, bytes: fs.readFileSync(file) }));
      const sourcePath = location.resolve(artifact.relativePath);
      const unavailableRoot = createTmpDir("acceptance-unavailable-evidence-");
      t.after(() => removeTmpDir(unavailableRoot));
      const unavailablePath = path.join(unavailableRoot, "artifact.json");
      fs.renameSync(sourcePath, unavailablePath);
      if (failure === "invalid") fs.writeFileSync(sourcePath, "{ externally corrupted canonical JSON\n");
      let outcome = null;
      let rejection = null;
      try { outcome = await scenario.invokeRegistered("run", "acceptance-review"); }
      catch (error) { rejection = error; }
      assert.ok(rejection || outcome?.ok === false, "invalid Version authority must be refused at the actual command/read boundary");
      const diagnostic = rejection?.message ?? outcome.errors.flatMap((entry) => entry.messages).join("\n");
      assert.match(diagnostic, failure === "missing" ? /Version authority path does not exist/
        : /invalid JSON|Unexpected token|Expected property name|artifact content does not match the catalog/);
      assert.equal(scenario.acceptanceCalls.length, 0);
      for (const { file, bytes } of authority) assert.deepEqual(fs.readFileSync(file), bytes,
        "read/admission refusal cannot fabricate a Result, receipt, Activity, Attempt or journal entry");
      fs.renameSync(unavailablePath, sourcePath);
      assert.deepEqual(fs.readFileSync(sourcePath), artifact.bytes);
      assert.deepEqual(scenario.reload().snapshot(), before);
      assert.equal(scenario.manager.readArtifact({ specId: scenario.specId, logicalKey: "acceptance.review",
        consumerNodeId: "final-regression", optional: true }), null);
      const recovered = await scenario.runRegistered("acceptance-review");
      assert.equal(recovered.verdict, "pass", JSON.stringify(recovered));
      assert.equal(scenario.acceptanceCalls.length, 1, "restored valid authority permits the first actual semantic execution");
    });
  }

  test("A05 acquired unavailable implementation Review holds Acceptance without provider calls until authorized complete evidence is regenerated", async (t) => {
    const originalSpawn = childProcess.spawnSync;
    let resumedExecution = null;
    const scenario = AcceptancePhaseScenario.create(t, {
      config: { lang: "en", type: "base", docs: { languages: ["en"], defaultLanguage: "en" } },
      sourceEffect: (effect, request, active) => {
        if (request.stepId === "implement") fs.appendFileSync(path.join(active.root, "src/implementation.js"),
          `// complete immutable implementation input\n${"// Preserve the required branch and complete its independent verification.\n".repeat(1500)}`);
        return effect;
      },
      reviewProcessResult: (stage, ordinal, options, _active, invocation) => {
        const worker = stage === "impl-review" && ordinal === 1 ? "acceptance-phase-review-worker.js" : "impl-phase-review-worker.js";
        return originalSpawn(process.execPath, [fileURLToPath(new URL(`../../support/${worker}`, import.meta.url)), ...invocation.args.slice(1)], {
          ...options, env: { ...options.env, SENNEL_IMPL_SCENARIO_RESPONSE: JSON.stringify({ blockingFindings: [], nonBlockingImprovements: [] }) },
        });
      },
      acceptanceResponse: (_ordinal, active) => {
        active.reload();
        resumedExecution = active.manager.readCurrentStepSettlement({ specId: active.specId, stepId: "acceptance-review" });
        return acceptanceProviderResponse(active);
      },
    });
    await scenario.advanceTo("impl-review");
    await scenario.executeCurrent();
    scenario.reload();
    const unavailableReview = scenario.commandArtifact("impl.review", "acceptance-review");
    descriptorProducer(scenario, unavailableReview, "impl-review");
    assert.ok(unavailableReview.payload.toolingOutcome, "actual bounded evaluator protocol must produce unavailable Review evidence");
    assert.equal(unavailableReview.payload.verdict, undefined, "a failed complete-input evaluation is never a semantic PASS");
    activateNonBlockingPolicy({ root: scenario.root, flowManager: scenario.manager,
      reason: "The user explicitly retains the bounded unavailable Review for independent Gate and final Acceptance assessment." });
    const decision = decisionContextForActiveFlow(scenario.root, scenario.manager.loadReadOnly(scenario.specId), scenario.manager);
    assert.equal(decision.resultKind, "tooling");
    recordNonBlockingDecision({ root: scenario.root, flowManager: scenario.manager, choice: "continue",
      reason: "Continue only with the exact unavailable-review obligation retained.",
      remainingRisk: "Acceptance must hold until complete implementation Review evidence is available.",
      expectEvidenceDigest: decision.evidenceDigest, expectIdentity: decision.identity().toJSON() });
    scenario.reload();
    await scenario.advanceTo("acceptance-review");
    scenario.reload();
    const acquired = await scenario.observeAcceptanceInput();
    assert.ok(acquired.mechanicalBlockers.some((entry) => entry.kind === "failed_review"));
    const originalAttempt = scenario.state().attempt;
    const originalSpec = scenario.artifact("spec.record");
    const heldResult = await scenario.runRegistered("acceptance-review");
    assert.equal(heldResult.verdict, "blocked", JSON.stringify(heldResult));
    scenario.reload();
    const blocked = savedReview(scenario);
    assert.equal(blocked.payload.verdict, "blocked");
    assert.equal(scenario.state().attempt.id, originalAttempt.id);
    assert.equal(scenario.acceptanceCalls.length, 0);
    const awaitProof = scenario.manager.readCurrentStepSettlement({ specId: scenario.specId, stepId: "acceptance-review" });
    assert.ok(awaitProof, "ACCEPTANCE_MECHANICAL_AWAIT_RECEIPT_MISSING: canonical blocked publication must save its exact Await Result and receipt");
    assert.equal(awaitProof.result.kind, "acceptance-review-mechanically-blocked");
    assert.equal(awaitProof.settlement.kind, "await");
    assert.equal(awaitProof.receipt.settlementKind, "await");
    const oldBinding = { runId: scenario.state().runId, specId: scenario.specId, stepId: "acceptance-review",
      attempt: { id: originalAttempt.id, sequence: originalAttempt.sequence } };
    definition.DraftStepSettlementReceipt.assertStored(awaitProof.receipt, {
      binding: oldBinding, result: awaitProof.result, settlement: awaitProof.settlement });
    scenario.assertResults(["acceptance-review"]);
    const oldReceiptBytes = Buffer.from(JSON.stringify(awaitProof.receipt), "utf8");
    const oldActivity = scenario.manager.activityLedger(scenario.specId).find((entry) => entry.id === awaitProof.activityId);
    assert.ok(oldActivity, "the canonical journal must retain the Await's genuine owning Activity");
    const oldActivityBytes = Buffer.from(JSON.stringify(oldActivity), "utf8");
    const oldJournalBytes = fs.readFileSync(scenario.manager.specLocation(scenario.specId).activitiesFile);
    const held = scenario.snapshot();
    let heldAction;
    await assert.doesNotReject(async () => { heldAction = await scenario.next(); },
      "ACCEPTANCE_MECHANICAL_AWAIT_MISSING: valid unavailable Review evidence must expose its saved safe hold after reload");
    assert.equal(heldAction.directive?.kind, "blocked");
    await scenario.dispatch(2);
    assert.equal(scenario.acceptanceCalls.length, 0);
    assert.deepEqual(scenario.reload().snapshot(), held);
    scenario.options.requirements = [{ id: "R1", desc: "Regenerate the completely reviewed requirement behavior.", task_ids: ["T1"],
      preimplementation_test_expectation: "pass" }];
    const authorized = await scenario.runRegistered("reopen-draft", { category: "spec-correction",
      reason: "The user authorizes regenerating complete review and requirement evidence for the held Acceptance.",
      expectRunId: scenario.state().runId, expectSpec: scenario.specId, expectNoIssue: true });
    assert.equal(authorized.mode, "spec-correction", JSON.stringify(authorized));
    scenario.reload();
    assert.equal(scenario.current(), "draft");
    await scenario.advanceTo("acceptance-review");
    scenario.reload();
    const currentReview = scenario.commandArtifact("impl.review", "acceptance-review");
    assert.equal(currentReview.payload.verdict, "PASS");
    assert.notEqual(currentReview.descriptor.activityId, unavailableReview.descriptor.activityId);
    assert.notEqual(scenario.artifact("spec.record").descriptor.activityId, originalSpec.descriptor.activityId);
    assert.notEqual(scenario.artifact("spec.record").descriptor.hash, originalSpec.descriptor.hash);
    assert.notEqual(scenario.state().attempt.id, originalAttempt.id);
    const newAttempt = scenario.state().attempt;
    const regeneratedInput = await scenario.observeAcceptanceInput();
    assert.notEqual(regeneratedInput.fingerprint.hash, blocked.payload.repairFingerprint);
    const resumed = await scenario.runRegistered("acceptance-review");
    assert.equal(resumed.verdict, "pass", JSON.stringify(resumed));
    scenario.reload();
    assert.notEqual(savedReview(scenario).payload.repairFingerprint, blocked.payload.repairFingerprint);
    assert.equal(scenario.acceptanceCalls.length, 1);
    assert.ok(resumedExecution, "the one actual new provider invocation must observe a durably claimed execution generation");
    assert.equal(resumedExecution.result.kind, "acceptance-review-execution-required");
    assert.equal(resumedExecution.settlement.kind, "execution");
    assert.equal(resumedExecution.receipt.executionLifecycle?.phase, "claimed");
    assert.equal(resumedExecution.receipt.binding.attemptId, newAttempt.id);
    assert.equal(resumedExecution.receipt.binding.attemptSequence, newAttempt.sequence);
    assert.equal(resumedExecution.receipt.executionLifecycle.binding.inputDigest, regeneratedInput.fingerprint.hash);
    definition.DraftStepSettlementReceipt.assertStored(resumedExecution.receipt, {
      binding: { ...oldBinding, attempt: { id: newAttempt.id, sequence: newAttempt.sequence } },
      result: resumedExecution.result, settlement: resumedExecution.settlement });
    const executionGeneration = resumedExecution.receipt.executionLifecycle.binding.executionGeneration;
    assert.ok(Number.isSafeInteger(executionGeneration) && executionGeneration >= 0);
    assert.notDeepEqual({ attemptId: newAttempt.id, sequence: newAttempt.sequence, executionGeneration }, {
      attemptId: originalAttempt.id, sequence: originalAttempt.sequence,
      executionGeneration: awaitProof.receipt.executionLifecycle?.binding.executionGeneration ?? null });
    definition.DraftStepSettlementReceipt.assertStored(awaitProof.receipt, {
      binding: oldBinding, result: awaitProof.result, settlement: awaitProof.settlement });
    assert.throws(() => definition.DraftStepSettlementReceipt.assertStored(awaitProof.receipt, {
      binding: { ...oldBinding, attempt: { id: newAttempt.id, sequence: newAttempt.sequence } },
      result: awaitProof.result, settlement: awaitProof.settlement }),
    /receipt binding is invalid/, "old Await authorization cannot be reused for the regenerated Attempt");
    assert.deepEqual(Buffer.from(JSON.stringify(awaitProof.receipt), "utf8"), oldReceiptBytes);
    const retainedActivity = scenario.manager.activityLedger(scenario.specId).find((entry) => entry.id === awaitProof.activityId);
    assert.deepEqual(Buffer.from(JSON.stringify(retainedActivity), "utf8"), oldActivityBytes);
    const currentJournal = fs.readFileSync(scenario.manager.specLocation(scenario.specId).activitiesFile);
    assert.deepEqual(currentJournal.subarray(0, oldJournalBytes.length), oldJournalBytes,
      "regeneration preserves the exact historical Await Activity and receipt bytes in the append-only journal");
    scenario.assertResults(["acceptance-review"], { terminal: false });
    scenario.assertResults(["acceptance-review"]);
  });

  test("A05 genuine failed tests remain FAIL through result Review and deny Acceptance provider/consumer admission", async (t) => {
    const scenario = AcceptancePhaseScenario.fromSeed(t, seed);
    // The immutable seed already passed real Requirement Review/Gate. Losing
    // the implementation now is lawful external source drift; Retro selects
    // fresh 03 execution of those genuine promoted tests, which records FAIL.
    fs.renameSync(path.join(scenario.root, "src/implementation.js"), path.join(scenario.root, "src/implementation.missing"));
    assert.equal((await scenario.runRegistered("retro")).result, "recovered");
    scenario.reload();
    assert.equal(scenario.current(), "test-execute");
    await scenario.advanceTo("test-result-review");
    scenario.reload();
    const failed = scenario.commandArtifact("test.execute", "test-result-review");
    descriptorProducer(scenario, failed, "test-execute");
    assert.equal(failed.payload.process.exitCode, 1);
    assert.equal(failed.payload.summary[0].result, "fail");
    await scenario.executeCurrent();
    scenario.reload();
    const resultReview = scenario.commandArtifact("test.result.review", "impl-review");
    descriptorProducer(scenario, resultReview, "test-result-review");
    assert.equal(resultReview.payload.verdict, "pass", "valid failure observations are preserved as trusted evidence");
    assert.equal(resultReview.payload.testExecute.producerActivityId, failed.descriptor.activityId);
    assert.equal(scenario.commandArtifact("test.execute", "impl-review").payload.summary[0].result, "fail");
    assert.notEqual(scenario.state().findNode("retro").status, "done");
    const before = scenario.snapshot();
    const refused = await scenario.runRegistered("acceptance-review");
    assert.equal(refused.ok, false, "failed upstream evidence cannot authorize direct Acceptance outside its selected route");
    assert.equal(scenario.acceptanceCalls.length, 0);
    assert.deepEqual(scenario.reload().snapshot(), before, "failed evidence admission cannot invent an Acceptance Activity/Attempt/receipt");
    assert.equal(scenario.manager.readArtifact({ specId: scenario.specId, logicalKey: "acceptance.review",
      consumerNodeId: "final-regression", optional: true }), null);
  });

  test("A05 real bounded Acceptance batches require a durable claim before first call and cannot resume unsaved partial provider output after reload", async (t) => {
    const calls = [];
    const limit = new PromptRequestLimit({ maxCharacters: 16_000 });
    const executionLimit = new PromptExecutionLimit({ maxRequestCharacters: limit.maxCharacters,
      maxProviderCallCount: 100, maxProtocolRetryCount: 0, maxSynthesisCallCount: 32 });
    const lost = new UnknownProviderFailure({ message: "The second Acceptance provider response was lost before publication." });
    const scenario = AcceptancePhaseScenario.fromSeed(t, seed, { providerOptions: {
      promptCharacterLimit: () => scenario.current() === "acceptance-review" ? limit.maxCharacters : null },
      acceptanceProvider: (prompt, invocation, active) => {
        active.reload();
        calls.push({ prompt, schema: invocation.jsonSchema,
          snapshot: active.snapshot(), claim: active.manager.readCurrentStepSettlement({ specId: active.specId, stepId: "acceptance-review" }) });
        if (calls.length === 2) throw lost;
        assert.equal(calls.length, 1, "an unsaved memory-only batch cannot be automatically called again");
        const ids = invocation.jsonSchema.properties.observations.items.properties.sourceRef.enum;
        return JSON.stringify({ observations: ids.map((sourceRef) => ({ sourceRef,
          facts: ["PARTIAL_ACCEPTANCE_OBSERVATION_MUST_STAY_MEMORY_ONLY"] })) });
      } });
    // Legitimate source drift at the real Retro frontier chooses its existing
    // rewind. The large changed source then reaches fresh 03 producers; no
    // completed evidence or impossible lifecycle is constructed for batching.
    fs.appendFileSync(path.join(scenario.root, "src/implementation.js"),
      `// complete current source explanation\n${"// Preserve the required behavior and its independently verified branch.\n".repeat(1_500)}`);
    assert.equal((await scenario.runRegistered("retro")).result, "recovered");
    scenario.reload();
    assert.equal(scenario.current(), "test-execute");
    await scenario.advanceTo("acceptance-review");
    scenario.reload();
    const acquired = await scenario.observeAcceptanceInput();
    assert.deepEqual(acquired.mechanicalBlockers, []);
    const plan = new AcceptanceEvidenceExecutionPlan(acquired, { limit, executionLimit });
    assert.ok(plan.observationPlan.batches.length >= 2,
      "the lawful acquired evidence must require multiple actual production map batches");
    const originalAttempt = scenario.state().attempt;
    const outcome = await scenario.runRegistered("acceptance-review");
    assert.equal(calls.length, 2, "one complete map response precedes the actual second provider interruption");
    // Observe first, let the external failure occur, then assert the durable
    // producer contract. A missing claim is never simulated by throwing an
    // assertion inside the provider before it could execute.
    const claim = calls[0].claim;
    assert.ok(claim,
      "ACCEPTANCE_EXECUTION_CLAIM_MISSING: the first actual provider call must follow a saved exact execution claim");
    assert.equal(claim.result.kind, "acceptance-review-execution-required");
    assert.equal(claim.receipt.executionLifecycle?.phase, "claimed");
    assert.match(claim.receipt.id, /\S+/);
    assert.equal(claim.receipt.binding.runId, scenario.state().runId);
    assert.equal(claim.receipt.binding.specId, scenario.specId);
    assert.equal(claim.receipt.binding.attemptId, originalAttempt.id);
    assert.equal(claim.receipt.binding.attemptSequence, originalAttempt.sequence);
    assert.equal(claim.receipt.executionLifecycle.binding.inputDigest, acquired.fingerprint.hash);
    assert.ok(calls[1].claim);
    assert.equal(calls[1].claim.receipt.id, claim.receipt.id);
    assert.deepEqual(calls[1].snapshot, calls[0].snapshot,
      "partial map success and remaining prompt budget must not acquire fabricated canonical progress");
    assert.equal(outcome.ok, false);
    assert.equal(outcome.errors[0].code, "PROMPT_BATCH_EXECUTION_INCOMPLETE");
    assert.match(outcome.errors[0].messages.join("\n"), new RegExp(lost.code),
      "the actual batch failure must preserve its original external provider cause");
    scenario.reload();
    assert.equal(scenario.current(), "acceptance-review");
    assert.equal(scenario.state().attempt.id, originalAttempt.id);
    assert.equal(scenario.state().attempt.consumption.semantic, originalAttempt.consumption.semantic);
    assert.notEqual(scenario.state().findNode("acceptance-review").status, "done");
    assert.equal(scenario.state().findNode("final-regression").status, "pending");
    assert.equal(scenario.manager.readArtifact({ specId: scenario.specId, logicalKey: "acceptance.review",
      consumerNodeId: "final-regression", optional: true }), null, "unsaved map responses are never partial Acceptance evidence");
    const stopped = scenario.snapshot();
    assert.equal(JSON.stringify(stopped).includes("PARTIAL_ACCEPTANCE_OBSERVATION_MUST_STAY_MEMORY_ONLY"), false);
    const reloadedAction = await scenario.next();
    assert.ok(["blocked", "await_user_decision"].includes(reloadedAction.directive?.kind),
      "an interrupted, unpersisted provider generation must expose the Definition's safe hold");
    await scenario.dispatch(2);
    assert.equal(calls.length, 2, "fresh manager must safely stop instead of fabricating memory-only batch resume");
    assert.equal(scenario.acceptanceCalls.length, 2);
    assert.deepEqual(scenario.reload().snapshot(), stopped);
    scenario.assertResults(["acceptance-review"], { terminal: false });
    scenario.assertResults(["acceptance-review"]);
  });
});

test("A03 guarded Spec correction republishes Requirement tests and rejects old question, risk decision and report identities", async (t) => {
  const question = (revision) => ({ state: "CandidateQuestion", id: "q1", category: "user-visible-behavior",
    question: "Which requirement behavior must be preserved?", revision, provenance: { producer: "draft-worker" },
    evidenceDigest: (revision === 0 ? "a" : "b").repeat(64) });
  const draftResponse = (revision) => async (request) => {
    if (request.stepId === "draft") fs.writeFileSync(requestPayloadPath(request, "draft.json"),
      `${JSON.stringify(canonicalDraftDocument({ questions: [question(revision)] }))}\n`);
  };
  const producer = AcceptancePhaseScenario.create(t, { autoApprove: false, beforeSeal: draftResponse(0),
    acceptanceResponse: (_ordinal, active) => acceptanceProviderResponse(active, { status: "notVerifiable" }) });
  await producer.advanceTo("draft-refine");
  await producer.executeCurrent();
  producer.reload();
  const originalQuestionAction = await producer.next();
  assert.equal(originalQuestionAction.directive?.kind, "await_draft_question");
  const answered = await producer.invokeRegistered("set", "draft-answer", {
    questionRevision: originalQuestionAction.directive.questionRevision, answer: "Preserve the original requirement.", why: "It matches the current request.",
  }, ["q1"]);
  assert.equal(answered.status, "answered", JSON.stringify(answered));
  await producer.advanceTo("approval");
  await producer.approve();
  await producer.advanceTo("acceptance-decision");
  producer.reload();
  const originalSpec = producer.artifact("spec.record");
  const originalPlan = producer.plan();
  const originalTests = producer.commandArtifact("test.execute", "acceptance-review");
  const originalAcceptance = savedReview(producer);
  assert.equal((await producer.acceptDecision("accept_risk_and_continue")).choice, "accept_risk_and_continue");
  producer.reload();
  const originalDecision = producer.commandArtifact("acceptance.decision", "final-regression");
  assert.equal(fs.lstatSync(path.join(producer.root, ".git")).isDirectory(), true,
    "the standalone producer must own regular Git metadata before its immutable seed is copied");
  const copy = new SeedWorkRoot(producer.root, { prefix: "sennel-spec-correction-seed-" });
  t.after(() => copy.cleanup());
  const seed = Object.freeze({ root: copy.root, specId: producer.specId, frontier: "final-regression",
    snapshot: producer.snapshot(), options: producer.options });
  // The report is produced in a separate legal continuation of the same
  // immutable frontier. The correction branch remains at final-regression,
  // where the existing authorized reopen route applies.
  const reportBranch = AcceptancePhaseScenario.fromSeed(t, seed);
  const execFile = childProcess.execFile;
  let regressionCalls = 0;
  const regressionProcess = t.mock.method(childProcess, "execFile", (command, args, options, callback) => {
    if (options.cwd !== reportBranch.root || command !== "npm") return execFile(command, args, options, callback);
    regressionCalls += 1;
    // External process boundary only; production still captures started,
    // exit, raw log, classification, execution binding and user authority.
    return execFile(process.execPath, ["-e", "process.stderr.write('ERR_ASSERTION\\nsrc/implementation.js: required behavior remains missing.\\n'); process.exit(1);"], options, callback);
  });
  syncBuiltinESMExports();
  const failed = await reportBranch.runRegistered("final-regression");
  assert.equal(failed.result, "fail", JSON.stringify(failed));
  assert.equal(regressionCalls, 1);
  reportBranch.reload();
  const firstFailure = reportBranch.commandArtifact("final.regression").payload;
  assert.equal(firstFailure.failureKind, "caused_by_current_change");
  const repairClaim = await new RunClaimNextActionCommand().execute(reportBranch.context());
  assert.equal(repairClaim.ok, true, JSON.stringify(repairClaim));
  reportBranch.reload();
  const retried = await reportBranch.runRegistered("final-regression");
  regressionProcess.mock.restore(); syncBuiltinESMExports();
  assert.equal(retried.result, "fail", JSON.stringify(retried));
  assert.equal(regressionCalls, 2);
  reportBranch.reload();
  const failureChoice = await reportBranch.next();
  assert.equal(failureChoice.directive?.kind, "await_user_decision");
  assert.equal(failureChoice.directive.actionPrompt.choices[0].actionId, "ACCEPT_FINAL_REGRESSION_FAILURE");
  const proceeded = await reportBranch.runRegistered("final-regression", { recordAndProceed: true,
    recordCategory: "out_of_scope", recordEvidence: "The user explicitly accepts the exact current-change failure after its bounded repair is exhausted.",
    remainingRisk: "The original regression remains failed and must not be accepted for a different publication." });
  assert.equal(proceeded.failedRecorded, true, JSON.stringify(proceeded));
  reportBranch.reload();
  const oldRegressionArtifact = reportBranch.commandArtifact("final.regression", "report");
  const oldRegressionAcceptance = oldRegressionArtifact.payload;
  assert.equal(oldRegressionAcceptance.result, "fail");
  assert.equal(oldRegressionAcceptance.selectedAction, "explicit-record-and-proceed");
  assertAcceptanceFinalRegressionEvidence(reportBranch, oldRegressionArtifact,
    { result: "fail", exitCode: 1, failureKind: "caused_by_current_change" });
  await assert.doesNotReject(() => reportBranch.advanceTo("finalize-commit"),
    "ACCEPTED_FAIL_REPORT_PRODUCER_MISSING: the genuine explicitly accepted FAIL must authorize the normal report producer");
  const oldReport = JSON.parse(reportBranch.artifact("report").bytes);
  RunReportCommand.validateFinalEvidence(oldReport, { root: reportBranch.root, artifactRoot: reportBranch.root });
  const correction = AcceptancePhaseScenario.fromSeed(t, seed, { beforeSeal: draftResponse(2),
    requirements: [{ id: "R1", desc: "Preserve the corrected requirement behavior.", task_ids: ["T1"],
      preimplementation_test_expectation: "pass" }],
    sourceEffect: (effect, request, active) => {
      if (["implement", "task-impl"].includes(request.stepId)) {
        fs.appendFileSync(path.join(active.root, request.taskId ? `src/task-${request.taskId}.js` : "src/implementation.js"),
          "// corrected Spec behavior and source generation\n");
      }
      return effect;
    } });
  const unchangedRegressionAcceptance = validateExplicitFinalRegressionProceed({ root: correction.root,
    artifact: oldRegressionAcceptance, repositoryBindingOptions: {
      pathspecExcludes: new RepairArtifactRegistry(correction.manager.specLocation(correction.specId).relativeSpecFile).gitPathspecExcludes() } });
  assert.equal(unchangedRegressionAcceptance.ok, true,
    "the old accepted FAIL must match this same source generation before its authorized Spec correction");
  const oldSpecSource = oldReport.data.binding.sourceArtifacts[0];
  assert.equal(oldSpecSource.path, path.posix.join(correction.manager.specLocation(correction.specId).relativeDirectory,
    originalSpec.descriptor.relativePath));
  assert.equal(oldSpecSource.sha256, correction.artifact("spec.record").descriptor.hash,
    "the report's bound original Spec must match this generation before correction; sibling later publications are not assumed present");
  const reopened = await correction.runRegistered("reopen-draft", { category: "spec-correction",
    reason: "The user authorizes a correction to the original requirement.", expectRunId: correction.state().runId,
    expectSpec: correction.specId, expectNoIssue: true });
  assert.equal(reopened.mode, "spec-correction", JSON.stringify(reopened));
  correction.reload();
  assert.equal(correction.current(), "draft", "Acceptance cannot invent a direct Spec repair route");
  assert.equal(correction.manager.activityLedger(correction.specId).at(-1).transition.operation, "reopen_draft_spec_correction");
  await correction.advanceTo("draft-refine");
  await correction.executeCurrent();
  correction.reload();
  const correctedQuestionAction = await correction.next();
  assert.equal(correctedQuestionAction.directive?.kind, "await_draft_question");
  const beforeOldAnswer = correction.snapshot();
  const staleAnswer = await correction.invokeRegistered("set", "draft-answer", {
    questionRevision: originalQuestionAction.directive.questionRevision, answer: "Preserve the original requirement.", why: "Old question publication.",
  }, ["q1"]);
  assert.equal(staleAnswer.ok, false);
  assert.equal(staleAnswer.errors[0].code, "DRAFT_ANSWER_NOT_SELECTED");
  assert.deepEqual(correction.reload().snapshot(), beforeOldAnswer);
  const corrected = await correction.invokeRegistered("set", "draft-answer", {
    questionRevision: correctedQuestionAction.directive.questionRevision, answer: "Preserve the corrected requirement.", why: "The user authorized this exact new question.",
  }, ["q1"]);
  assert.equal(corrected.status, "answered", JSON.stringify(corrected));
  await correction.advanceTo("approval");
  await correction.approve();
  await correction.advanceTo("acceptance-decision");
  correction.reload();
  const currentSpec = correction.artifact("spec.record");
  assert.notEqual(currentSpec.descriptor.activityId, originalSpec.descriptor.activityId);
  assert.notEqual(currentSpec.descriptor.hash, originalSpec.descriptor.hash);
  const currentPlan = correction.plan();
  assert.notDeepEqual(currentPlan.toJSON(), originalPlan.toJSON());
  const approvedReview = correction.manager.readCurrentSpecReview({ specId: correction.specId, consumerNodeId: "approval" });
  assert.ok(approvedReview);
  assert.deepEqual(currentPlan.specRevision.toJSON(), approvedReview.review.identity.toJSON(),
    "Requirement plan must use the exact current approved Spec revision");
  const approvedSnapshot = correction.manager.readArtifact({ specId: correction.specId, logicalKey: "spec.snapshot",
    parameters: { revision: currentPlan.specRevision.revision.toString() }, consumerNodeId: "approval" });
  assert.equal(approvedSnapshot.descriptor.hash, currentPlan.specRevision.digest);
  assert.equal(approvedSnapshot.bytes.length, currentPlan.specRevision.byteLength);
  assert.equal(currentPlan.specRevision.specId, correction.specId);
  assert.deepEqual(JSON.parse(approvedSnapshot.bytes).requirements, JSON.parse(currentSpec.bytes).requirements);
  for (const item of currentPlan.workItems) assert.ok(item.specRevision.equals(currentPlan.specRevision));
  const currentTests = correction.commandArtifact("test.execute", "acceptance-review");
  assert.notEqual(currentTests.descriptor.activityId, originalTests.descriptor.activityId);
  assert.notEqual(currentTests.payload.repairFingerprint, originalTests.payload.repairFingerprint);
  const currentReview = savedReview(correction);
  assert.notEqual(currentReview.descriptor.activityId, originalAcceptance.descriptor.activityId);
  assert.notEqual(currentReview.descriptor.hash, originalDecision.payload.acceptanceReviewDigest);
  assert.equal(currentReview.payload.userDecision, null);
  const beforeDecision = correction.snapshot();
  assert.throws(() => acceptanceDecisionRouteFacts({ state: correction.state(), review: currentReview.payload,
    reviewDescriptor: currentReview.descriptor, spec: JSON.parse(currentSpec.bytes),
    choice: originalDecision.payload.choice,
    decisionRecord: { choice: originalDecision.payload.choice, reviewArtifactDigest: originalDecision.payload.acceptanceReviewDigest } }),
  /not bound to canonical review evidence/, "the actual same-authority decision consumer rejects the old saved review identity");
  assert.deepEqual(correction.reload().snapshot(), beforeDecision);
  const staleRegressionAcceptance = validateExplicitFinalRegressionProceed({ root: correction.root,
    artifact: oldRegressionAcceptance, repositoryBindingOptions: {
      pathspecExcludes: new RepairArtifactRegistry(correction.manager.specLocation(correction.specId).relativeSpecFile).gitPathspecExcludes() } });
  assert.equal(staleRegressionAcceptance.ok, false, "new Spec/source publication cannot reuse the prior explicit failed-regression acceptance");
  assert.match(staleRegressionAcceptance.reason, /worktree.*stale|stale.*worktree/i,
    "stale source binding must refuse before a missing raw log could hide the intended contract");
  assert.throws(() => RunReportCommand.validateFinalEvidence(oldReport, { root: correction.root, artifactRoot: correction.root }),
    { code: "REPORT_BINDING_STALE", message: `REPORT_BINDING_STALE: source artifact has changed: ${oldSpecSource.path}` },
    "the real final-evidence consumer rejects the changed Spec before any unavailable sibling publication");
  assert.equal((await correction.acceptDecision("accept_risk_and_continue")).choice, "accept_risk_and_continue");
  await correction.advanceTo("finalize-commit");
  correction.reload();
  assert.notDeepEqual(JSON.parse(correction.artifact("report").bytes).data.binding, oldReport.data.binding);
  correction.assertResults(["retro", "acceptance-review", "acceptance-decision", "final-regression", "report"]);
});

// These independent registry checks run in addition to real producers; a
// missing kind cannot prevent a different scenario from reaching its boundary.
for (const contract of acceptancePhaseResultContracts) {
  test(`A00 ${contract.stepId} persists the fixed ${contract.kind}/${contract.type}/${contract.className} registry contract`, () => {
    contract.registration();
  });
}
test("A00 Acceptance Definition provides one Result-only settlement selector", () => {
  assert.equal(typeof definition.settleAcceptanceStepResult, "function",
    "ACCEPTANCE_PHASE_SETTLEMENT_API_MISSING: settleAcceptanceStepResult(stepId, concreteResult)");
});
